services:
  db:
    image: postgres:18.4-alpine
    container_name: library-catalog-db
    environment:
      POSTGRES_USER: library
      POSTGRES_PASSWORD: library
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql
volumes:
  db-data:
